### ISSUE TITLE
Create homepage to select what to do

### ISSUE THREAD

**Issue by V-ed** [V-ed/Scouts-Elections#10]
Two options would be given :
- Start new Elections
- Load previous Elections
    - This would load a database file, which in turn loads the pre-results-page and subsequent calls to view the actual results.
    - If the data in the file is not good, don't load the database.
    - If the voting session of that database is unfinished, load the voting system with the candidates and unfinished voters.

All options should be written in French.

The buttons should be centered, with a title (`h1`) at the top saying "`Élections Scouts`", the title also centered.

### TODO

- [x] Design page with bootstrap
- [x] Test if page switching mechanism works
- [ ] Load file
    - [ ] Check file data if crucial datapoints are missing
    - [ ] Check if voting session of that database is unfinished

**Comment by V-ed** [comment]
Closed by #20, the homepage is created and designed (somewhat poorly but eh), so this issue can be closed with the remaining tasks in the new issue.
