### ISSUE TITLE
Add handler to load a database file into the program

### ISSUE THREAD

**Issue by V-ed** [V-ed/Scouts-Elections#20]
This issue finalizes #10 and would therefore be implemented in the homepage.

I will probably use https://www.dropzonejs.com/ which would allow us to drag and drop file or select it in our file system.

Loading the file using only javascript should be possible using something along the lines of https://stackoverflow.com/a/14155586/3784670 , but that answer will need to be modified to fit our needs.

### TODO :

- [x] Load file
    - [x] Check file data if crucial datapoints are missing
- [x] Setup page based on database state
    - [x] Check if voting session of that database is unfinished
    - [x] If votes finished or skipped, load `pre_results_page` with the data using the view_switcher
    - [x] If votes are not finished and is not skipped, load `voting_page` with the data using the view_switcher
