### ISSUE TITLE
Make app mobile friendly

### ISSUE THREAD

**Issue by V-ed** [V-ed/Scouts-Elections#30]
### TODOs :

- [x] Voting session
    - [x] Fix layout of showing candidates
        - [x] Fix padding
        - [x] Show only one or two candidates per row
    - [x] Introduce new system to go to the next voter (cannot press space on mobile without an input method)
        - I will probably go for some sort of "`hold the top portion of the screen for 3 seconds`" or something like that
            - https://stackoverflow.com/a/19371884 (detect touchhold)
        - https://stackoverflow.com/a/36673184 (detect if touchscreen enabled)
- [x] Verify other screens if broken layout on mobile
