### ISSUE TITLE
Handle shared election page closing or going to local election

### ISSUE THREAD

**Issue by V-ed** [V-ed/Scouts-Elections#74]
This is a continuation of PR #68

## TODOs

- [ ] Handle user leaving current page
    - [ ] Send request (beacon) when leaving page to tell the server a user has left, so a new seat should be available if it was taken and not fulfilled
        - [ ] To handle beacon send failures and leaving the server in an uncertain state, create an UUID locally and send this UUID in the beacon request, saving it to the database created
            - If the server recieves the data, store the UUID to know which unhandled user is currently trying to vote
            - This would mean that to finish the election, the database that was generated automatically would need to be used again on this election, which the server would understand is the user joining back, giving back the seat for this unhandled leave
            - Therefore, if sending the UUID to the server and the server doesn't find this UUID, the server will know there was a problem and to allocate a seat already taken (if that was the case!) to this device. If a seat wasn't taken by this device, then allocate a new seat if one is free, otherwise return the data that the election is finished.
            - https://github.com/V-ed/Scouts-Elections-Server/issues/15
- [ ] Allow to return to an ongoing shared election if page was closed
    - [ ] In this special case, the shared election code should be added to the data
    - [ ] When loading that data with a shared election code, delete the code from the data
    - [ ] Verify to not take another seat when loading the election if a seat was already taken
    - [ ] Add loading icon when making request
    - [ ] Add request errors handling
        - [ ] If election not reachable, propose to do it locally instead
    - [ ] If election already ended, propose to either go to results or to do this saved election locally
        - [ ] The option to go to the results would be the primary action
- [ ] Allow post-shared-election-view to force a seat to be freed
    - This would be helpful if a device that had a seat simply dies or skips locally.
    - [ ] Add a confirmation that explains that this action is dangerous
    - [ ] Add request errors handling
        - [ ] If errors, mentions that you can simply go to current local data, mentionning that verifying will also download the latest candidates data

**Comment by V-ed** [comment]
The data object would have a new field, named `currentlyHasSeat` that would track if the current election has a seat taken. This will be used to load the election back again if the connection is broken.

---

Actually... thinking about it, we already kinda handle problems of sending votes by storing the votes array in a temporary variable and querying that variable in te `go_to_next_voter` method...

I should just simply use that variable to try again on load if there were errors! That variable should therefore be added to the data when there is errors, so I can handle it later on. Don't take a seat, just send the votes that were saved on error (maybe after confirmation?).

That would actually fix all the things! Maybe you shouldn't even need that much of a lease-seat after all! But it would be useful if a device dies, not only that it loses internet.
